CREATE OR REPLACE SEQUENCE COPILOTS_CHATS_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE OR REPLACE TABLE COPILOTS_CHATS (
    ID NUMBER(38,0) NOT NULL DEFAULT COPILOTS_CHATS_SEQ.NEXTVAL,
    CHAT_ID STRING NOT NULL UNIQUE,  -- ✅ Must be UNIQUE for FK reference
    TITLE STRING,
    USER_ID STRING NOT NULL,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);


CREATE OR REPLACE SEQUENCE COPILOTS_CHAT_MESSAGES_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE OR REPLACE TABLE COPILOTS_CHAT_MESSAGES (
    ID NUMBER(38,0) NOT NULL DEFAULT COPILOTS_CHAT_MESSAGES_SEQ.NEXTVAL,
    CHAT_ID STRING NOT NULL,
    MESSAGE STRING,
    TRANSLATE_TO_ENGLISH STRING,
    QUERIES TEXT,
    RELATED_QUERIES TEXT,
    ERROR STRING,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (CHAT_ID) REFERENCES COPILOTS_CHATS(CHAT_ID)
);


ALTER TABLE COPILOTS_CHAT_MESSAGES
ADD COLUMN ROLE STRING;

-- Step 1: Create sequence for auto-increment ID
CREATE OR REPLACE SEQUENCE COPILOT_COLLECTIONS_SEQ
START WITH 1
INCREMENT BY 1;

-- Step 2: Create table
CREATE OR REPLACE TABLE COPILOT_COLLECTIONS (
    ID NUMBER(38,0) NOT NULL DEFAULT COPILOT_COLLECTIONS_SEQ.NEXTVAL,
    USER_ID STRING NOT NULL,
    TITLE STRING NOT NULL,
    DESCRIPTION STRING,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS CHATGPT_API_LOGS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SESSION_ID STRING,                         -- Grouping for conversations
    USER_ID STRING,                            -- Optional, if tracking users
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    
    PROMPT_TEXT TEXT,                          -- Full prompt text
    RESPONSE_TEXT TEXT,                        -- ChatGPT's response
    MODEL_USED STRING,                         -- e.g., gpt-4, gpt-4o
    TEMPERATURE FLOAT,                         -- API parameter used
    MAX_TOKENS NUMBER,                         -- API parameter used

    PROMPT_TOKENS NUMBER,                      -- Tokens used for prompt
    COMPLETION_TOKENS NUMBER,                  -- Tokens used in response
    TOTAL_TOKENS NUMBER,                       -- Total tokens used

    API_STATUS STRING,                         -- success/failure
    ERROR_MESSAGE TEXT,                        -- If API failed
    LATENCY_MS NUMBER                          -- Time taken to get response
);


-- Add CHAT_ID column
ALTER TABLE COPILOT_COLLECTIONS
ADD COLUMN CHAT_ID STRING;

-- Add MESSAGE_ID column
ALTER TABLE COPILOT_COLLECTIONS
ADD COLUMN MESSAGE_ID NUMBER(38, 0);

-- Add MESSAGE_CONTENT column
ALTER TABLE COPILOT_COLLECTIONS
ADD COLUMN MESSAGE_CONTENT STRING;

-- Add DELETE_CONTENT column with default FALSE
ALTER TABLE COPILOT_COLLECTIONS
ADD COLUMN DELETE_CONTENT STRING;

-- Add PREFERENCES column as VARIANT (for JSON)
ALTER TABLE COPILOT_COLLECTIONS
ADD COLUMN PREFERENCES VARIANT;

-- Add foreign key constraint for CHAT_ID
ALTER TABLE COPILOT_COLLECTIONS
ADD CONSTRAINT FK_COLLECTION_CHAT_ID
FOREIGN KEY (CHAT_ID) REFERENCES COPILOTS_CHATS(ID);

-- Add foreign key constraint for MESSAGE_ID
ALTER TABLE COPILOT_COLLECTIONS
ADD CONSTRAINT FK_COLLECTION_MESSAGE_ID
FOREIGN KEY (MESSAGE_ID) REFERENCES COPILOTS_CHAT_MESSAGES(ID);

-- Step 1: Add COLLECTION_ID column
ALTER TABLE COPILOTS_CHAT_MESSAGES
ADD COLUMN COLLECTION_ID STRING;

ALTER TABLE COPILOTS_CHAT_MESSAGES
ADD COLUMN EXPLANATION STRING;

-- Step 2: Add foreign key constraint referencing COPILOT_COLLECTIONS
ALTER TABLE COPILOTS_CHAT_MESSAGES
ADD CONSTRAINT FK_CHAT_MESSAGE_COLLECTION_ID
FOREIGN KEY (COLLECTION_ID) REFERENCES COPILOT_COLLECTIONS(ID);
