CREATE OR REPLACE SEQUENCE COPILOTS_CHATS_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE OR REPLACE TABLE COPILOTS_CHATS (
    ID NUMBER(38,0) NOT NULL DEFAULT COPILOTS_CHATS_SEQ.NEXTVAL,
    CHAT_ID STRING NOT NULL UNIQUE,  -- ✅ Must be UNIQUE for FK reference
    TITLE STRING,
    USER_ID STRING NOT NULL,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);


CREATE OR REPLACE SEQUENCE COPILOTS_CHAT_MESSAGES_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE OR REPLACE TABLE COPILOTS_CHAT_MESSAGES (
    ID NUMBER(38,0) NOT NULL DEFAULT COPILOTS_CHAT_MESSAGES_SEQ.NEXTVAL,
    CHAT_ID STRING NOT NULL,
    MESSAGE STRING,
    TRANSLATE_TO_ENGLISH STRING,
    QUERIES TEXT,
    RELATED_QUERIES TEXT,
    ERROR STRING,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (CHAT_ID) REFERENCES COPILOTS_CHATS(CHAT_ID)
);


ALTER TABLE COPILOTS_CHAT_MESSAGES
ADD COLUMN ROLE STRING;

-- Step 1: Create sequence for auto-increment ID
CREATE OR REPLACE SEQUENCE COPILOT_COLLECTIONS_SEQ
START WITH 1
INCREMENT BY 1;

-- Step 2: Create table
CREATE OR REPLACE TABLE COPILOT_COLLECTIONS (
    ID NUMBER(38,0) NOT NULL DEFAULT COPILOT_COLLECTIONS_SEQ.NEXTVAL,
    USER_ID STRING NOT NULL,
    TITLE STRING NOT NULL,
    DESCRIPTION STRING,
    CREATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);
